import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedAccount {
  code: string;
  name: string;
  nameEn?: string;
  accountClass: string;
  mainGroup?: string;
  subGroup?: string;
  nature: "مدين" | "دائن";
  statementType: "قائمة المركز المالي" | "قائمة الدخل";
  level: number;
  parentCode?: string;
  isGroup: boolean;
  isSystem: boolean;
}

const standardAccounts: SeedAccount[] = [
  // ──────────────────────────────────────────
  // 1. الأصول (ASSETS)
  // ──────────────────────────────────────────
  {
    code: "1",
    name: "الأصول",
    nameEn: "Assets",
    accountClass: "الأصول",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 1,
    isGroup: true,
    isSystem: true,
  },

  // 11. الأصول الثابتة
  {
    code: "11",
    name: "الأصول الثابتة",
    nameEn: "Fixed Assets",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "1",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "1101",
    name: "الأراضي",
    nameEn: "Lands",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1102",
    name: "المباني والإنشاءات",
    nameEn: "Buildings",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1103",
    name: "الآلات والمعدات",
    nameEn: "Machinery & Equipment",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1104",
    name: "السيارات ووسائل النقل",
    nameEn: "Vehicles",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1105",
    name: "الأثاث والتجهيزات المكتبية",
    nameEn: "Furniture & Fixtures",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1106",
    name: "أجهزة الكمبيوتر والبرمجيات",
    nameEn: "Computers & IT Equipment",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1107",
    name: "الديكورات والتركيبات",
    nameEn: "Decorations & Installations",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1108",
    name: "ماكينات ومعدات تشغيل",
    nameEn: "Operating Machines",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "1109",
    name: "مجمع إهلاك الأصول الثابتة",
    nameEn: "Accumulated Depreciation",
    accountClass: "الأصول",
    mainGroup: "الأصول الثابتة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "11",
    isGroup: false,
    isSystem: true,
  },

  // 12. الأصول المتداولة
  {
    code: "12",
    name: "الأصول المتداولة",
    nameEn: "Current Assets",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "1",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "1201",
    name: "النقدية وما في حكمها",
    nameEn: "Cash & Cash Equivalents",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "النقدية بالصندوق",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "120101",
    name: "الخزينة الرئيسية",
    nameEn: "Main Safe",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "النقدية بالصندوق",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1201",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120102",
    name: "الخزينة الفرعية",
    nameEn: "Sub Safe",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "النقدية بالصندوق",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1201",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120103",
    name: "عهد نقدية مؤقتة",
    nameEn: "Petty Cash",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "النقدية بالصندوق",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1201",
    isGroup: false,
    isSystem: true,
  },

  // 1202. البنوك والمحافظ
  {
    code: "1202",
    name: "البنوك والمحافظ المالية",
    nameEn: "Banks & E-Wallets",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "البنوك",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "120201",
    name: "الحسابات الجارية بالبنوك",
    nameEn: "Bank Current Accounts",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "البنوك",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1202",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120202",
    name: "حسابات التوفير والودائع",
    nameEn: "Savings & Deposits",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "البنوك",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1202",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120203",
    name: "المحافظ الإلكترونية والمدفوعات الرقمية",
    nameEn: "Digital Wallets & Cash",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "البنوك",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1202",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120204",
    name: "حساب الهيئة القومية للبريد",
    nameEn: "Postal Account",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "البنوك",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1202",
    isGroup: false,
    isSystem: true,
  },

  // 1203. أوراق القبض
  {
    code: "1203",
    name: "أوراق القبض (شيكات تحت التحصيل)",
    nameEn: "Notes Receivable",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: false,
    isSystem: true,
  },

  // 1204. المخزون
  {
    code: "1204",
    name: "المخزون السلعي",
    nameEn: "Inventory",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "المخزون",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "120401",
    name: "مخزون بضاعة تامة الصنع",
    nameEn: "Finished Goods Inventory",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "المخزون",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1204",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120402",
    name: "مخزون خامات ومواد أولية",
    nameEn: "Raw Materials Inventory",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "المخزون",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1204",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120403",
    name: "مخزون مهمات وقطع غيار",
    nameEn: "Spare Parts & Supplies",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "المخزون",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1204",
    isGroup: false,
    isSystem: true,
  },

  // 1205. العملاء
  {
    code: "1205",
    name: "العملاء (حساب المراقبة)",
    nameEn: "Accounts Receivable (Control)",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "العملاء",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "120501",
    name: "عملاء محليون",
    nameEn: "Local Customers",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "العملاء",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1205",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120502",
    name: "عملاء تصدير وخارجيون",
    nameEn: "Foreign Customers",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "العملاء",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1205",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120503",
    name: "مبيعات نقدية (عميل نقدي)",
    nameEn: "Cash Customers",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    subGroup: "العملاء",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1205",
    isGroup: false,
    isSystem: true,
  },

  // 1206. أرصدة مدينة أخرى
  {
    code: "1206",
    name: "أرصدة مدينة أخرى",
    nameEn: "Other Debit Balances",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "12",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "120601",
    name: "إيراد مستحق",
    nameEn: "Accrued Revenues",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1206",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120602",
    name: "مصروف مدفوع مقدماً",
    nameEn: "Prepaid Expenses",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1206",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120603",
    name: "تأمينات لدى الغير",
    nameEn: "Deposits with Others",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1206",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120604",
    name: "سلف وذمم الموظفين",
    nameEn: "Employee Advances",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1206",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "120605",
    name: "مدينون متنوعون",
    nameEn: "Miscellaneous Debtors",
    accountClass: "الأصول",
    mainGroup: "الأصول المتداولة",
    nature: "مدين",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "1206",
    isGroup: false,
    isSystem: true,
  },

  // ──────────────────────────────────────────
  // 2. الخصوم (LIABILITIES)
  // ──────────────────────────────────────────
  {
    code: "2",
    name: "الخصوم",
    nameEn: "Liabilities",
    accountClass: "الخصوم",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 1,
    isGroup: true,
    isSystem: true,
  },
  {
    code: "21",
    name: "الخصوم المتداولة",
    nameEn: "Current Liabilities",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "2",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "2101",
    name: "الموردين (حساب المراقبة)",
    nameEn: "Accounts Payable (Control)",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    subGroup: "الموردين",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "21",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "210101",
    name: "موردون محليون",
    nameEn: "Local Suppliers",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    subGroup: "الموردين",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2101",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210102",
    name: "موردون خارجيون",
    nameEn: "Foreign Suppliers",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    subGroup: "الموردين",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2101",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210103",
    name: "مشتريات نقدية (مورد نقدي)",
    nameEn: "Cash Purchases (Cash Supplier)",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    subGroup: "الموردين",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2101",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "2102",
    name: "أوراق الدفع (شيكات تحت الصرف)",
    nameEn: "Notes Payable",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "21",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "2103",
    name: "مصروفات مستحقة",
    nameEn: "Accrued Expenses",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "21",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "210301",
    name: "مرتبات وأجور مستحقة",
    nameEn: "Accrued Salaries",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2103",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210302",
    name: "إيجارات مستحقة",
    nameEn: "Accrued Rent",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2103",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "2104",
    name: "أرصدة دائنة أخرى والضرائب",
    nameEn: "Other Creditors & Taxes",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "21",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "210401",
    name: "مصلحة الضرائب - ضريبة القيمة المضافة",
    nameEn: "VAT Payable",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2104",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210402",
    name: "مصلحة الضرائب - كسب العمل",
    nameEn: "Payroll Tax Payable",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2104",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210403",
    name: "الهيئة القومية للتأمينات الاجتماعية",
    nameEn: "Social Insurance Payable",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2104",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "210404",
    name: "دائنون متنوعون",
    nameEn: "Miscellaneous Creditors",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 4,
    parentCode: "2104",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "2105",
    name: "قروض وتسهيلات قصيرة الأجل",
    nameEn: "Short-term Loans",
    accountClass: "الخصوم",
    mainGroup: "الخصوم المتداولة",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "21",
    isGroup: false,
    isSystem: true,
  },

  // 22. الخصوم طويلة الأجل
  {
    code: "22",
    name: "الخصوم طويلة الأجل",
    nameEn: "Long-term Liabilities",
    accountClass: "الخصوم",
    mainGroup: "الخصوم طويلة الأجل",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "2",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "2201",
    name: "قروض بنكية طويلة الأجل",
    nameEn: "Long-term Bank Loans",
    accountClass: "الخصوم",
    mainGroup: "الخصوم طويلة الأجل",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "22",
    isGroup: false,
    isSystem: true,
  },

  // ──────────────────────────────────────────
  // 3. حقوق الملكية (EQUITY)
  // ──────────────────────────────────────────
  {
    code: "3",
    name: "حقوق الملكية",
    nameEn: "Equity",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 1,
    isGroup: true,
    isSystem: true,
  },
  {
    code: "31",
    name: "رأس المال",
    nameEn: "Capital",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "3",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "32",
    name: "جاري الشركاء / صاحب المنشأة",
    nameEn: "Partners' Current Accounts",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "3",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "3201",
    name: "جاري الشريك الرئيسي",
    nameEn: "Main Partner Current Account",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "32",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "33",
    name: "الاحتياطيات",
    nameEn: "Reserves",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "3",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "3301",
    name: "الاحتياطي القانوني",
    nameEn: "Legal Reserve",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "33",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "3302",
    name: "الاحتياطي العام",
    nameEn: "General Reserve",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 3,
    parentCode: "33",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "34",
    name: "الأرباح المحتجزة / المرحلة",
    nameEn: "Retained Earnings",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "3",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "35",
    name: "أرباح (خسائر) العام الحالي",
    nameEn: "Current Year Profit / Loss",
    accountClass: "حقوق الملكية",
    nature: "دائن",
    statementType: "قائمة المركز المالي",
    level: 2,
    parentCode: "3",
    isGroup: false,
    isSystem: true,
  },

  // ──────────────────────────────────────────
  // 4. الإيرادات (REVENUE)
  // ──────────────────────────────────────────
  {
    code: "4",
    name: "الإيرادات",
    nameEn: "Revenue",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 1,
    isGroup: true,
    isSystem: true,
  },
  {
    code: "41",
    name: "إيرادات النشاط الرئيسي",
    nameEn: "Operating Revenue",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "4",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "4101",
    name: "إيراد المبيعات",
    nameEn: "Sales Revenue",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "41",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "4102",
    name: "إيراد تقديم خدمات",
    nameEn: "Services Revenue",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "41",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "4103",
    name: "مردودات ومسموحات المبيعات",
    nameEn: "Sales Returns & Allowances",
    accountClass: "الإيرادات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "41",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "4104",
    name: "الخصم المسموح به",
    nameEn: "Sales Discounts Allowed",
    accountClass: "الإيرادات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "41",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "42",
    name: "إيرادات أخرى متنوعة",
    nameEn: "Other Revenues",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "4",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "4201",
    name: "أرباح بيع أصول ثابتة",
    nameEn: "Gain on Sale of Assets",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "42",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "4202",
    name: "إيرادات استثمارات وفوائد بنكية",
    nameEn: "Interest & Investment Income",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "42",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "4203",
    name: "إيرادات عرضية ومتنوعة",
    nameEn: "Miscellaneous Revenue",
    accountClass: "الإيرادات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "42",
    isGroup: false,
    isSystem: true,
  },

  // ──────────────────────────────────────────
  // 5. المصروفات (EXPENSES)
  // ──────────────────────────────────────────
  {
    code: "5",
    name: "المصروفات",
    nameEn: "Expenses",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 1,
    isGroup: true,
    isSystem: true,
  },

  // 51. تكلفة النشاط والمبيعات
  {
    code: "51",
    name: "تكلفة النشاط والمبيعات",
    nameEn: "Cost of Goods Sold (COGS)",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "5",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "5101",
    name: "المشتريات",
    nameEn: "Purchases",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5102",
    name: "مصاريف نقل وشحن المشتريات (نولون)",
    nameEn: "Freight-In Purchases",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5103",
    name: "جمارك ورسوم استيراد",
    nameEn: "Customs & Import Duties",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5104",
    name: "مردودات ومسموحات المشتريات",
    nameEn: "Purchases Returns & Allowances",
    accountClass: "المصروفات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5105",
    name: "الخصم المكتسب",
    nameEn: "Purchases Discounts Received",
    accountClass: "المصروفات",
    nature: "دائن",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },

  {
    code: "5106",
    name: "تغير مخزون آخر الفترة",
    nameEn: "Periodic Inventory Change",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "51",
    isGroup: false,
    isSystem: true,
  },

  // 52. مصاريف البيع والتسويق
  {
    code: "52",
    name: "مصاريف البيع والتسويق",
    nameEn: "Selling & Marketing Expenses",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "5",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "5201",
    name: "حملات الدعاية والتسويق الرقمي",
    nameEn: "Marketing & Digital Ads",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "52",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5202",
    name: "رواتب وعمولات فريق المبيعات",
    nameEn: "Sales Salaries & Commissions",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "52",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5203",
    name: "مصاريف شحن وتوصيل المبيعات",
    nameEn: "Delivery & Shipping Out",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "52",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5204",
    name: "مواد تعبئة وتغليف",
    nameEn: "Packaging Materials",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "52",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5205",
    name: "إيجار معارض ومنافذ بيع",
    nameEn: "Showroom Rent",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "52",
    isGroup: false,
    isSystem: true,
  },

  // 53. المصروفات العمومية والإدارية
  {
    code: "53",
    name: "مصروفات إدارية وعمومية",
    nameEn: "General & Administrative Expenses",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "5",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "5301",
    name: "الأجور والرواتب الإدارية",
    nameEn: "Administrative Salaries",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5302",
    name: "إيجار المقرات الإدارية",
    nameEn: "Office Rent",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5303",
    name: "كهرباء ومياه وغاز",
    nameEn: "Utilities (Electricity & Water)",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5304",
    name: "تليفونات وإنترنت واشتراكات رقمية",
    nameEn: "Telephone & Internet",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5305",
    name: "أدوات مكتبية ومطبوعات ورقية",
    nameEn: "Stationery & Printing",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5306",
    name: "مصروفات ضيافة وبوفيه ونظافة",
    nameEn: "Hospitality & Cleaning",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5307",
    name: "مصروفات وعمولات بنكية",
    nameEn: "Bank Charges & Fees",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5308",
    name: "اشتراك برامج وحلول سحابية",
    nameEn: "Software & Cloud Subscriptions",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5309",
    name: "استشارات قانونية ومحاسبية وتدقيق",
    nameEn: "Legal & Accounting Consultations",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5310",
    name: "إصلاحات وصيانة دورية عامة",
    nameEn: "Repairs & Maintenance",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5311",
    name: "انتقالات وسفريات ومحروقات سيارات",
    nameEn: "Transportation & Fuel",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5312",
    name: "تأمينات اجتماعية - حصة المنشأة",
    nameEn: "Company Social Insurance",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5313",
    name: "قسط إهلاك الأصول الثابتة",
    nameEn: "Depreciation Expense",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5314",
    name: "ديون معدومة",
    nameEn: "Bad Debts",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5315",
    name: "رسوم وغرامات حكومية وتراخيص",
    nameEn: "Government Licenses & Fees",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5316",
    name: "مصروفات إدارية ونثرية متنوعة",
    nameEn: "Miscellaneous Expenses",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "53",
    isGroup: false,
    isSystem: true,
  },

  // 54. مصروفات التشغيل والإنتاج
  {
    code: "54",
    name: "مصروفات التشغيل والإنتاج",
    nameEn: "Operating & Production Expenses",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 2,
    parentCode: "5",
    isGroup: true,
    isSystem: true,
  },
  {
    code: "5401",
    name: "أجور ومرتبات عمال التشغيل والإنتاج",
    nameEn: "Factory Labor Wages",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5402",
    name: "إيجار المصنع والورش ومواقع التشغيل",
    nameEn: "Factory & Workshop Rent",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5403",
    name: "كهرباء وقوى محركة للمصنع والآلات",
    nameEn: "Industrial Power & Electricity",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5404",
    name: "زيوت ووقود وصيانة آلات الإنتاج",
    nameEn: "Machine Oil, Fuel & Maintenance",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5405",
    name: "تشغيل وتصنيع خارجي لدى الغير",
    nameEn: "Subcontracting & External Processing",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
  {
    code: "5406",
    name: "مهمات وأدوات أمن صناعي وسلامة",
    nameEn: "Safety & Industrial Supplies",
    accountClass: "المصروفات",
    nature: "مدين",
    statementType: "قائمة الدخل",
    level: 3,
    parentCode: "54",
    isGroup: false,
    isSystem: true,
  },
];

async function main() {
  console.log("Seeding standard chart of accounts...");

  // 1. Create or get default demo company
  const company = await prisma.company.upsert({
    where: { id: 1 },
    update: {},
    create: {
      name: process.env.COMPANY_NAME || "الشركة",

      currency: "EGP",
      isDefault: true,
    },
  });

  console.log(`Using company: ${company.name} (ID: ${company.id})`);

  // 2. Insert accounts in hierarchical order (Level 1 -> 2 -> 3 -> 4)
  const sortedAccounts = [...standardAccounts].sort(
    (a, b) => a.level - b.level,
  );

  let inserted = 0;
  for (const acc of sortedAccounts) {
    await prisma.account.upsert({
      where: {
        companyId_code: {
          companyId: company.id,
          code: acc.code,
        },
      },
      update: {},
      create: {
        companyId: company.id,
        code: acc.code,
        name: acc.name,
        nameEn: acc.nameEn,
        accountClass: acc.accountClass,
        mainGroup: acc.mainGroup,
        subGroup: acc.subGroup,
        nature: acc.nature,
        statementType: acc.statementType,
        level: acc.level,
        parentCode: acc.parentCode,
        isGroup: acc.isGroup,
        isSystem: acc.isSystem,
      },
    });
    inserted++;
  }

  console.log(`✅ Successfully seeded ${inserted} standard accounts!`);
}

main()
  .catch((e) => {
    console.error("Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
